apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    name: nginx
spec:
  containers:
  - name: naginx-container
    image: nginx:latest
    resources:
      #limits:
        #memory: ""
        #cpu: ""
    ports:
      - containerPort: 80
